apiVersion: v1
kind: Pod
metadata:
  name: flume
  labels:
    k8s-app: flume
spec:
  containers:
    - name: es17
      image: elasticsearch:1.7.6
      ports:
        - containerPort: 9200
    - name: es60
      image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
      env:
       - name: http.port
         value: "9400"
       - name: transport.tcp.port
         value: "9500"
      ports:
        - containerPort: 9400
    - name: flume
      image: szaharici/flume-es6:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 5160
---
kind: Service
apiVersion: v1
metadata:
  name: flume
spec:
  selector:
    k8s-app: flume 
  ports:
    - protocol: TCP
      port: 5160
      targetPort: 5160
      name: flume
    - protocol: TCP
      port: 9200
      targetPort: 9200
      name: es17
    - protocol: TCP
      port: 9400
      targetPort: 9400
      name: es60
  type: NodePort
